/*
 * EssSuite.java
 * JUnit based test
 *
 * Created on April 28, 2007, 12:59 PM
 */

package ess;

import junit.framework.*;

/**
 *
 * @author Administrator
 */
public class EssSuite extends TestCase {
    
    public EssSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("EssSuite");
        suite.addTest(ess.InternalPanelBeanTest.suite());
        suite.addTest(ess.floorIndicatorBeanTest.suite());
        suite.addTest(ess.elevatorAppletTest.suite());
        suite.addTest(ess.ElevatorBeanTest.suite());
        return suite;
    }
    
}
