/*
 * ElevatorMainForm.java
 *
 * Created on February 10, 2007, 10:34 PM
 */

package ess;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import javax.swing.DefaultListModel;
import org.jdesktop.layout.LayoutStyle;

/**
 *
 * @author  Administrator
 */
public class ElevatorMainForm extends javax.swing.JPanel{
    
    /** Creates new form ElevatorMainForm */
    private DefaultListModel listModel;
    
    private DefaultListModel listModelEle1;
    private DefaultListModel listModelEle2;
    
    
    public ElevatorMainForm() {
        initComponents();
        //for external request  pool
        listModel = new DefaultListModel();
        
        //for internal request pool
        listModelEle1 = new DefaultListModel();
        listModelEle2  = new DefaultListModel();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        elevatorBean1 = new ess.ElevatorBean();
        elevatorBean2 = new ess.ElevatorBean();
        jScrollPane1 = new javax.swing.JScrollPane();
        JList_Elevator_Pool = new javax.swing.JList();
        JLabel_Elevator_Pool = new javax.swing.JLabel();
        floorPanel2UP = new javax.swing.JButton();
        floorPanel2Down = new javax.swing.JButton();
        floorPanel3UP = new javax.swing.JButton();
        floorPanel3Down = new javax.swing.JButton();
        floorPanel1UP = new javax.swing.JButton();
        floorPanel4Down = new javax.swing.JButton();
        E2floorPanel4Down = new javax.swing.JButton();
        E2floorPanel3UP = new javax.swing.JButton();
        E2floorPanel3Down = new javax.swing.JButton();
        E2floorPanel2UP = new javax.swing.JButton();
        E2floorPanel2Down = new javax.swing.JButton();
        E2floorPanel1UP = new javax.swing.JButton();
        internalPanelBean1 = new ess.InternalPanelBean();
        JList_Elevator1_Internal_Request_Pool = new javax.swing.JList();
        internalPanelBean2 = new ess.InternalPanelBean();
        JList_Elevator2_Internal_Request_Pool = new javax.swing.JList();
        JLabel_Elevator_Pool1 = new javax.swing.JLabel();
        JLabel_Elevator_Pool2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(elevatorBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 670));

        add(elevatorBean2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 160, 640));

        JList_Elevator_Pool.setBackground(new java.awt.Color(51, 51, 51));
        JList_Elevator_Pool.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JList_Elevator_Pool.setFont(new java.awt.Font("Tahoma", 1, 11));
        JList_Elevator_Pool.setForeground(new java.awt.Color(153, 255, 0));
        jScrollPane1.setViewportView(JList_Elevator_Pool);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 190, 130));

        JLabel_Elevator_Pool.setBackground(new java.awt.Color(51, 51, 0));
        JLabel_Elevator_Pool.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Elevator_Pool.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Elevator_Pool.setText("Elevator Request Pool");
        JLabel_Elevator_Pool.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JLabel_Elevator_Pool.setOpaque(true);
        add(JLabel_Elevator_Pool, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 20));

        floorPanel2UP.setText("U");
        floorPanel2UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorPanel2UPMouseClicked(evt);
            }
        });
        floorPanel2UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorPanel2UPActionPerformed(evt);
            }
        });

        add(floorPanel2UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 50, 20));

        floorPanel2Down.setText("D");
        floorPanel2Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorPanel2DownMouseClicked(evt);
            }
        });

        add(floorPanel2Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 50, 20));

        floorPanel3UP.setText("U");
        floorPanel3UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorPanel3UPMouseClicked(evt);
            }
        });

        add(floorPanel3UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 50, 20));

        floorPanel3Down.setText("D");
        floorPanel3Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorPanel3DownMouseClicked(evt);
            }
        });

        add(floorPanel3Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 50, 20));

        floorPanel1UP.setText("U");
        floorPanel1UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorPanel1UPMouseClicked(evt);
            }
        });

        add(floorPanel1UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 50, 20));

        floorPanel4Down.setText("D");
        floorPanel4Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floorPanel4DownMouseClicked(evt);
            }
        });

        add(floorPanel4Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 50, 20));

        E2floorPanel4Down.setText("D");
        E2floorPanel4Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2floorPanel4DownMouseClicked(evt);
            }
        });

        add(E2floorPanel4Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 50, 20));

        E2floorPanel3UP.setText("U");
        E2floorPanel3UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2floorPanel3UPMouseClicked(evt);
            }
        });

        add(E2floorPanel3UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 50, 20));

        E2floorPanel3Down.setText("D");
        E2floorPanel3Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2floorPanel3DownMouseClicked(evt);
            }
        });

        add(E2floorPanel3Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 50, 20));

        E2floorPanel2UP.setText("U");
        E2floorPanel2UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2floorPanel2UPMouseClicked(evt);
            }
        });
        E2floorPanel2UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2floorPanel2UPActionPerformed(evt);
            }
        });

        add(E2floorPanel2UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 50, 20));

        E2floorPanel2Down.setText("D");
        E2floorPanel2Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2floorPanel2DownMouseClicked(evt);
            }
        });

        add(E2floorPanel2Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 50, 20));

        E2floorPanel1UP.setText("U");
        E2floorPanel1UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2floorPanel1UPMouseClicked(evt);
            }
        });

        add(E2floorPanel1UP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 580, 50, 20));

        internalPanelBean1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internalPanelBean1MouseClicked(evt);
            }
        });

        add(internalPanelBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 150, 130));

        JList_Elevator1_Internal_Request_Pool.setBackground(new java.awt.Color(51, 51, 51));
        JList_Elevator1_Internal_Request_Pool.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JList_Elevator1_Internal_Request_Pool.setFont(new java.awt.Font("Tahoma", 1, 11));
        JList_Elevator1_Internal_Request_Pool.setForeground(new java.awt.Color(153, 255, 0));
        add(JList_Elevator1_Internal_Request_Pool, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 150, 130));

        internalPanelBean2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internalPanelBean2MouseClicked(evt);
            }
        });

        add(internalPanelBean2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 150, 130));

        JList_Elevator2_Internal_Request_Pool.setBackground(new java.awt.Color(51, 51, 51));
        JList_Elevator2_Internal_Request_Pool.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JList_Elevator2_Internal_Request_Pool.setFont(new java.awt.Font("Tahoma", 1, 11));
        JList_Elevator2_Internal_Request_Pool.setForeground(new java.awt.Color(153, 255, 0));
        add(JList_Elevator2_Internal_Request_Pool, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 150, 130));

        JLabel_Elevator_Pool1.setBackground(new java.awt.Color(51, 51, 0));
        JLabel_Elevator_Pool1.setFont(new java.awt.Font("Tahoma", 0, 10));
        JLabel_Elevator_Pool1.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Elevator_Pool1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Elevator_Pool1.setText("Elevator 1 Internal Request Pool");
        JLabel_Elevator_Pool1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JLabel_Elevator_Pool1.setOpaque(true);
        add(JLabel_Elevator_Pool1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 150, 20));

        JLabel_Elevator_Pool2.setBackground(new java.awt.Color(51, 51, 0));
        JLabel_Elevator_Pool2.setFont(new java.awt.Font("Tahoma", 0, 10));
        JLabel_Elevator_Pool2.setForeground(new java.awt.Color(255, 255, 255));
        JLabel_Elevator_Pool2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Elevator_Pool2.setText("Elevator 2 Internal Request Pool");
        JLabel_Elevator_Pool2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JLabel_Elevator_Pool2.setOpaque(true);
        add(JLabel_Elevator_Pool2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 150, 20));

    }// </editor-fold>//GEN-END:initComponents

    private void internalPanelBean2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internalPanelBean2MouseClicked
// TODO add your handling code here:
        JButton srcObject = (JButton)evt.getSource();
         if (srcObject.getText().equals("Open")) {
            //Open the door
            elevatorBean2.setDoorRequest(true);
        }
        else  if(srcObject.getText().equals("Close")) {
            
            //Close the door
            elevatorBean2.setDoorRequest(false);
        }
        else  if(srcObject.getText().equals("Stop")) {
            
            //Stop the elevator for half minute
            elevatorBean2.setStopRequest(true);
        }
        
         else if(srcObject.getText().equals("Emergency"))
        {
            if (elevatorBean2.isEmergencySet()==false)
            {
                //Call for Emergency
                elevatorBean2.calllForEmergency(elevatorBean2.getCurrentFloor());
            }
            else
            {
                //Release Emergency if pressed twise
                elevatorBean2.releaseEmergency();
            }
        }
        else
        {
            switch(Integer.parseInt(srcObject.getText()))
            {
                case 1:     elevatorBean2.addToRequestPool(1,elevatorBean2.getElevatorDirection());
                            addToInternalRequestPool(1,2);
                            break;
                case 2:     elevatorBean2.addToRequestPool(2,elevatorBean2.getElevatorDirection());
                            addToInternalRequestPool(2,2);
                            break;
                case 3:     elevatorBean2.addToRequestPool(3,elevatorBean2.getElevatorDirection());
                            addToInternalRequestPool(3,2);
                            break;
                case 4:     elevatorBean2.addToRequestPool(4,elevatorBean2.getElevatorDirection());
                            addToInternalRequestPool(4,2);
                            break;
            }
        }
    }//GEN-LAST:event_internalPanelBean2MouseClicked

    private void internalPanelBean1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internalPanelBean1MouseClicked
// TODO add your handling code here:
        JButton srcObject = (JButton)evt.getSource();
        
        if (srcObject.getText().equals("Open")) {
            //Open the door
            elevatorBean1.setDoorRequest(true);
        }
        else  if(srcObject.getText().equals("Close")) {
            
            //Close the door
            elevatorBean1.setDoorRequest(false);
        }
        else  if(srcObject.getText().equals("Stop")) {
            
            //Stop the elevator for half minute
            elevatorBean1.setStopRequest(true);
        }
        else if(srcObject.getText().equals("Emergency"))
        {
            if (elevatorBean1.isEmergencySet()==false)
            {
                //Call for Emergency
                elevatorBean1.calllForEmergency(elevatorBean1.getCurrentFloor());
            }
            else
            {
                //Release Emergency if pressed twise
                elevatorBean1.releaseEmergency();
            }
        }
        else {
            switch(Integer.parseInt(srcObject.getText()))
            {
                case 1:     elevatorBean1.addToRequestPool(1,elevatorBean1.getElevatorDirection());
                            addToInternalRequestPool(1,1);
                            break;
                case 2:     elevatorBean1.addToRequestPool(2,elevatorBean1.getElevatorDirection());
                            addToInternalRequestPool(2,1);
                            break;
                case 3:     elevatorBean1.addToRequestPool(3,elevatorBean1.getElevatorDirection());
                            addToInternalRequestPool(3,1);
                            break;
                case 4:     elevatorBean1.addToRequestPool(4,elevatorBean1.getElevatorDirection());
                            addToInternalRequestPool(4,1);
                            break;
            }
        }
    }//GEN-LAST:event_internalPanelBean1MouseClicked

    private void E2floorPanel1UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2floorPanel1UPMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(1,true,2);
        elevatorBean2.addToRequestPool(1,false);
    }//GEN-LAST:event_E2floorPanel1UPMouseClicked

    private void E2floorPanel2DownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2floorPanel2DownMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(2,false,2);
        elevatorBean2.addToRequestPool(2,true);
    }//GEN-LAST:event_E2floorPanel2DownMouseClicked

    private void E2floorPanel2UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2floorPanel2UPActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_E2floorPanel2UPActionPerformed

    private void E2floorPanel2UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2floorPanel2UPMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(2,true,2);
        elevatorBean2.addToRequestPool(2,false);
    }//GEN-LAST:event_E2floorPanel2UPMouseClicked

    private void E2floorPanel3DownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2floorPanel3DownMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(3,false,2);
        elevatorBean2.addToRequestPool(3,true);
    }//GEN-LAST:event_E2floorPanel3DownMouseClicked

    private void E2floorPanel3UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2floorPanel3UPMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(3,true,2);
        elevatorBean2.addToRequestPool(3,false);
    }//GEN-LAST:event_E2floorPanel3UPMouseClicked

    private void E2floorPanel4DownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2floorPanel4DownMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(4,false,2);
        elevatorBean2.addToRequestPool(4,true);
    }//GEN-LAST:event_E2floorPanel4DownMouseClicked

    private void floorPanel2DownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorPanel2DownMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(2,false,1);
        elevatorBean1.addToRequestPool(2,true);

    }//GEN-LAST:event_floorPanel2DownMouseClicked

    private void floorPanel3DownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorPanel3DownMouseClicked
// TODO add your handling code here:

        addToExternalRequestPool(3,false,1);
        elevatorBean1.addToRequestPool(3,true);

    }//GEN-LAST:event_floorPanel3DownMouseClicked

    private void floorPanel3UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorPanel3UPMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(3,true,1);
        elevatorBean1.addToRequestPool(3,false);

    }//GEN-LAST:event_floorPanel3UPMouseClicked

    private void floorPanel2UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorPanel2UPMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(2,true,1);
        elevatorBean1.addToRequestPool(2,false);

    }//GEN-LAST:event_floorPanel2UPMouseClicked

    private void floorPanel1UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorPanel1UPMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(1,true,1);
        elevatorBean1.addToRequestPool(1,false);

    }//GEN-LAST:event_floorPanel1UPMouseClicked

    private void floorPanel4DownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floorPanel4DownMouseClicked
// TODO add your handling code here:
        addToExternalRequestPool(4,false,1);
        elevatorBean1.addToRequestPool(4,true);

    }//GEN-LAST:event_floorPanel4DownMouseClicked

    private void floorPanel2UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorPanel2UPActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_floorPanel2UPActionPerformed
    
    
    private void addToExternalRequestPool (int floornumber,boolean direction,int ElevatorNo)
    {
        String str;
        if (direction==true) {
            // from down to up
            if(ElevatorNo==1)
            {
                str= "E1 - Floor [" + floornumber + "] UP ";
            }
            else
            {
                str= "E2 - Floor [" + floornumber + "] UP ";
            }
        }
        else {
            //from up to down
            if(ElevatorNo==1) {
                str= "E1 - Floor [" + floornumber + "] DOWN ";
            }
            else {
                str= "E2 - Floor [" + floornumber + "] DOWN ";
            }
        }
        listModel.addElement(str);
        
        JList_Elevator_Pool.setModel(listModel);
    }

    private void addToInternalRequestPool (int floornumber,int ElevatorNo)
    {
        String str;
        str= "Floor [" + floornumber + "]";
        if(ElevatorNo==1) {
            listModelEle1.addElement(str);
            JList_Elevator1_Internal_Request_Pool.setModel(listModelEle1);
        }
        else if(ElevatorNo==2) {
            listModelEle2.addElement(str);
            JList_Elevator2_Internal_Request_Pool.setModel(listModelEle2);
        }        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton E2floorPanel1UP;
    private javax.swing.JButton E2floorPanel2Down;
    private javax.swing.JButton E2floorPanel2UP;
    private javax.swing.JButton E2floorPanel3Down;
    private javax.swing.JButton E2floorPanel3UP;
    private javax.swing.JButton E2floorPanel4Down;
    private javax.swing.JLabel JLabel_Elevator_Pool;
    private javax.swing.JLabel JLabel_Elevator_Pool1;
    private javax.swing.JLabel JLabel_Elevator_Pool2;
    private javax.swing.JList JList_Elevator1_Internal_Request_Pool;
    private javax.swing.JList JList_Elevator2_Internal_Request_Pool;
    private javax.swing.JList JList_Elevator_Pool;
    private ess.ElevatorBean elevatorBean1;
    private ess.ElevatorBean elevatorBean2;
    private javax.swing.JButton floorPanel1UP;
    private javax.swing.JButton floorPanel2Down;
    private javax.swing.JButton floorPanel2UP;
    private javax.swing.JButton floorPanel3Down;
    private javax.swing.JButton floorPanel3UP;
    private javax.swing.JButton floorPanel4Down;
    private ess.InternalPanelBean internalPanelBean1;
    private ess.InternalPanelBean internalPanelBean2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

        
}
