/*
 * InternalPanelBean.java
 *
 * Created on February 21, 2007, 11:10 AM
 */

package ess;

/**
 *
 * @author  Administrator
 */
public class InternalPanelBean extends javax.swing.JPanel {
    
    /** Creates new form InternalPanelBean */
    public InternalPanelBean() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnFloor2 = new javax.swing.JButton();
        btnFloor1 = new javax.swing.JButton();
        btnFloor3 = new javax.swing.JButton();
        btnFloor4 = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnEmergency = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBackground(new java.awt.Color(204, 204, 204));
        btnFloor2.setText("2");
        btnFloor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFloor2MouseClicked(evt);
            }
        });

        add(btnFloor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btnFloor1.setText("1");
        btnFloor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFloor1MouseClicked(evt);
            }
        });

        add(btnFloor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btnFloor3.setText("3");
        btnFloor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFloor3MouseClicked(evt);
            }
        });

        add(btnFloor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnFloor4.setText("4");
        btnFloor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFloor4MouseClicked(evt);
            }
        });

        add(btnFloor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnOpen.setText("Open");
        btnOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenMouseClicked(evt);
            }
        });

        add(btnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));

        btnClose.setText("Close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, -1));

        btnEmergency.setText("Emergency");
        btnEmergency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmergencyMouseClicked(evt);
            }
        });

        add(btnEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, -1));

        btnStop.setText("Stop");
        btnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopMouseClicked(evt);
            }
        });

        add(btnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void btnStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseClicked
// TODO add your handling code here:
            fireMouseListenerMouseClicked(evt);
    }//GEN-LAST:event_btnStopMouseClicked

    private void btnEmergencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmergencyMouseClicked
// TODO add your handling code here:
            fireMouseListenerMouseClicked(evt);
    }//GEN-LAST:event_btnEmergencyMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
// TODO add your handling code here:
    fireMouseListenerMouseClicked(evt);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenMouseClicked
// TODO add your handling code here:
        fireMouseListenerMouseClicked(evt);
    }//GEN-LAST:event_btnOpenMouseClicked

    private void btnFloor4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFloor4MouseClicked
// TODO add your handling code here:
        fireMouseListenerMouseClicked(evt);
    }//GEN-LAST:event_btnFloor4MouseClicked

    private void btnFloor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFloor3MouseClicked
// TODO add your handling code here:
        fireMouseListenerMouseClicked(evt);
    }//GEN-LAST:event_btnFloor3MouseClicked

    private void btnFloor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFloor2MouseClicked
// TODO add your handling code here:
         fireMouseListenerMouseClicked(evt);
    }//GEN-LAST:event_btnFloor2MouseClicked

    private void btnFloor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFloor1MouseClicked
// TODO add your handling code here:
        fireMouseListenerMouseClicked(evt);
    }//GEN-LAST:event_btnFloor1MouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEmergency;
    private javax.swing.JButton btnFloor1;
    private javax.swing.JButton btnFloor2;
    private javax.swing.JButton btnFloor3;
    private javax.swing.JButton btnFloor4;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnStop;
    // End of variables declaration//GEN-END:variables

    /**
     * Utility field holding list of MouseListeners.
     */
    private transient java.util.ArrayList mouseListenerList;

    /**
     * Registers MouseListener to receive events.
     * @param listener The listener to register.
     */
    public synchronized void addMouseListener(java.awt.event.MouseListener listener) {
        if (mouseListenerList == null ) {
            mouseListenerList = new java.util.ArrayList ();
        }
        mouseListenerList.add (listener);
    }

    /**
     * Removes MouseListener from the list of listeners.
     * @param listener The listener to remove.
     */
    public synchronized void removeMouseListener(java.awt.event.MouseListener listener) {
        if (mouseListenerList != null ) {
            mouseListenerList.remove (listener);
        }
    }

    /**
     * Notifies all registered listeners about the event.
     * 
     * @param event The event to be fired
     */
    private void fireMouseListenerMouseClicked(java.awt.event.MouseEvent event) {
        java.util.ArrayList list;
        synchronized (this) {
            if (mouseListenerList == null) return;
            list = (java.util.ArrayList)mouseListenerList.clone ();
        }
        for (int i = 0; i < list.size (); i++) {
            ((java.awt.event.MouseListener)list.get (i)).mouseClicked (event);
        }
    }


    
}
